@announcementId = 65c678ec90e44ea4b2b9f566

### Create

POST {{host}}/{{baseUrl}}/announcements
Content-Type: application/json

{
  "description": "This is a test announcement",
  "items": ["6659ef6226f1bb4053c32969"]
}

### Get All

GET {{host}}/{{baseUrl}}/announcements

### Delete

DELETE {{host}}/{{baseUrl}}/announcements/{{announcementId}}

### Delete Many

DELETE {{host}}/{{baseUrl}}/announcements
Content-Type: application/json

{
  "ids": ["665ad326b79da256d734d593", "665ae302635ebb4264588b9d"]
}