@announcementId = 65c678ec90e44ea4b2b9f566

### Create

POST {{host}}/{{baseUrl}}/announcements
Content-Type: application/json

{
  "description": "This is a test announcement",
  "items": ["6659ddf226f1bb4053c31c57", "6659ddf226f1bb4053c31c56", "6659ddf226f1bb4053c31c55"]
}

### Get All

GET {{host}}/{{baseUrl}}/announcements

### Delete

DELETE {{host}}/{{baseUrl}}/announcements/{{announcementId}}