### Register

POST {{host}}/{{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "user7",
  "password": "Password123!",
  "passwordConfirm": "Password123!",
  "email": "user7@email.com"
}

### Login

POST {{host}}/{{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Password123!"
}

### Logout

POST {{host}}/{{baseUrl}}/auth/logout