### Register

POST {{host}}/{{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "Password123!",
  "passwordConfirm": "Password123!",
  "email": "admin@email.com"
}

### Login

POST {{host}}/{{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "rescuer1",
  "password": "Password123!"
}

### Logout

POST {{host}}/{{baseUrl}}/auth/logout