@itemId = 65c675a8fa63db786131a811

### Find

GET {{host}}/{{baseUrl}}/items
#    ?name=Tampons
#    &category=65c674f2177263200fc1ea61

### Create

POST {{host}}/{{baseUrl}}/items
Content-Type: application/json

{
  "name": "Milko",
  "category": "65c675c7177263200fc1ea9c",
  "details": [
    {
      "name": "price",
      "value": "100"
    }
  ]
}

### Update

PATCH {{host}}/{{baseUrl}}/items/{{itemId}}
Content-Type: application/json

{
  "name": "Oreo",
  "quantity": 1
}

### Delete

DELETE {{host}}/{{baseUrl}}/items/{{itemId}}

### Delete multiple

DELETE {{host}}/{{baseUrl}}/items
Content-Type: application/json

{
  "ids": ["65c675a8fa63db786131a811"]
}