@requestId = 667ec6000153e4c573ba3af6

### Create

POST {{host}}/{{baseUrl}}/item-requests
Content-Type: application/json

{
  "item": "65c675a8fa63db786131a788",
  "peopleCount": 5
}

### Get all

GET {{host}}/{{baseUrl}}/item-requests
#    ?status=pending
#    &item=65c5fb76fa63db7861314a31
#    &citizen=65c5fb76fa63db7861314a31

### Get mine

GET {{host}}/{{baseUrl}}/item-requests/me
#    ?status=pending
#    &item=65c5fb76fa63db7861314a31

### Update status

PATCH {{host}}/{{baseUrl}}/item-requests/{{requestId}}/status
Content-Type: application/json

{
  "status": "accepted"
}

### Delete

DELETE {{host}}/{{baseUrl}}/item-requests/{{requestId}}