POST http://localhost:8000/api/auth/register
content-type: application/json

{
  "username": "admin",
  "password": "Password123!",
  "passwordConfirm": "Password123!",
  "email": "george@email.com"
}

###

POST http://localhost:8000/api/auth/login
content-type: application/json

{
  "username": "admin",
  "password": "Password123!"
}

###

GET http://localhost:8000/api/users/me

###

GET http://localhost:8000/api/users/650ae357db97ed89f70cb5f4