### Get me

GET {{host}}/{{baseUrl}}/users/me

### Update me

PATCH {{host}}/{{baseUrl}}/users/me
Content-Type: application/json

{
  "details": {
    "firstName": "George",
    "lastName": "Gkonis",
    "phoneNumber": "00306955773209",
    "address": "25is Martiou 13B, 14671 Athens, Greece"
  }
}

### Update my location

PATCH {{host}}/{{baseUrl}}/users/me/location
Content-Type: application/json

{
  "latitude": 37.983810,
  "longitude": 23.727539
}

### Delete me

DELETE {{host}}/{{baseUrl}}/users/me

### Create

POST {{host}}/{{baseUrl}}/users
Content-Type: application/json

{
  "username": "rescuer2",
  "password": "Password123!",
  "email": "rescuer2@email.com",
  "role": "rescuer"
}

### Get all

GET {{host}}/{{baseUrl}}/users

### Get

GET {{host}}/{{baseUrl}}/users/{{id}}

### Delete

DELETE {{host}}/{{baseUrl}}/users/{{id}}