### Get Me

GET {{host}}/{{baseUrl}}/users/me

### Update Me

PATCH {{host}}/{{baseUrl}}/users/me
Content-Type: application/json

{
  "username": "user2",
  "password": "Password123!"
}

### Delete Me

DELETE {{host}}/{{baseUrl}}/users/me

### Get All

GET {{host}}/{{baseUrl}}/users

### Get

GET {{host}}/{{baseUrl}}/users/{{id}}

### Delete

DELETE {{host}}/{{baseUrl}}/users/{{id}}