### Get Me

GET {{host}}/{{baseUrl}}/users/me

### Update Me

PATCH {{host}}/{{baseUrl}}/users/me
Content-Type: application/json

{
  "username": "admin",
  "password": "sdf!",
  "details": {
    "firstName": "George",
    "lastName": "Gkonis",
    "phoneNumber": "00306955773209",
    "address": "25is Martiou 13B, 14671 Athens, Greece"
  }
}

### Delete Me

DELETE {{host}}/{{baseUrl}}/users/me

### Create

POST {{host}}/{{baseUrl}}/users
Content-Type: application/json

{
  "username": "rescuer2",
  "password": "Password123!",
  "email": "rescuer2@email.com",
  "role": "rescuer"
}

### Get All

GET {{host}}/{{baseUrl}}/users

### Get

GET {{host}}/{{baseUrl}}/users/{{id}}

### Delete

DELETE {{host}}/{{baseUrl}}/users/{{id}}