@itemId = 5f5e3e3e75ef47b68360fbd3

### Upload categories and items

POST {{host}}/{{baseUrl}}/warehouse/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="data.json"
Content-Type: application/json

< C:\Users\georg\Programming\Webstorm\disaster-response-coordinator\data\data.json
--WebAppBoundary--

### Get categories

GET {{host}}/{{baseUrl}}/warehouse/categories
#    ?name=Food

### Get items

GET {{host}}/{{baseUrl}}/warehouse/items
#    ?category=9
#    &name=t22

### Add Category

POST {{host}}/{{baseUrl}}/warehouse/categories
Content-Type: application/json

{
    "id": "1",
    "name": "Food"
}

### Add item

POST {{host}}/{{baseUrl}}/warehouse/items
Content-Type: application/json

{
    "id": "2",
    "name": "Power",
    "category": "65c5524e75ef47b68360fbd3",
    "details": [
        {
            "name": "price",
            "value": "100"
        }
    ]
}

### Update item quantity

PATCH {{host}}/{{baseUrl}}/warehouse/items/{{itemId}}
Content-Type: application/json

{
  "quantity": 100
}

### Delete all categories and items

DELETE {{host}}/{{baseUrl}}/warehouse