
### Import data

PUT {{host}}/{{baseUrl}}/warehouse/import
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="data.json"
Content-Type: application/json

< D:\Webstorm\disaster-response-coordinator\data\data.json

### Export data

GET {{host}}/{{baseUrl}}/warehouse/export
Content-Type: application/json

### Delete data

DELETE {{host}}/{{baseUrl}}/warehouse